
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/sidebar";
import ClientProviders from "./client-provider";
import { useSession } from 'next-auth/react';
import Header from "@/components/header";
import Footer from "@/components/footer";
import HydrationZustand from "./Hydrated";
import { GlobalContextProvider } from "@/context/GlobalContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex h-screen w-full bg-gray-100">
          <HydrationZustand>

            <GlobalContextProvider>
              <>

                < Sidebar />
                <div className="flex flex-col h-full w-full ml-64">
                  <Header />
                  <div className="p-4">
                    {children}
                  </div>
                  <Footer />

                </div>
              </>
            </GlobalContextProvider>
          </HydrationZustand>
        </div>
        {/* </div> */}
      </body>
    </html >

  );



  return <p>Authenticated</p>

}




